version: '3'

networks:
  portfolio_net:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio_app
    image: portfolio_project-app
    networks:
      - portfolio_net

  nginx:
    image: nginx:alpine
    container_name: nginx_reverse_proxy
    ports:
      - "9090:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - portfolio_net
